#!/usr/bin/env python3
"""Regenerate manifest.json from the .xrcourse packages in this folder.

Run after adding or replacing a sample:

    python pre-built-samples/build_manifest.py

Title, chapter and section counts are read from each package, so the catalog
the app shows can never drift from the files. Subject labels are kept from the
existing manifest (or guessed from the filename prefix) since they are the one
piece of metadata a package does not carry.
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
MANIFEST = HERE / "manifest.json"

SUBJECTS = {
    "phys": {"zh": "物理", "en": "Physics"},
    "chem": {"zh": "化学", "en": "Chemistry"},
    "bio": {"zh": "生物", "en": "Biology"},
    "geo": {"zh": "地球科学", "en": "Geoscience"},
    "mecha": {"zh": "机械", "en": "Mechanical"},
    "math": {"zh": "数学", "en": "Mathematics"},
}


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main() -> None:
    previous = {}
    if MANIFEST.exists():
        old = json.loads(MANIFEST.read_text(encoding="utf-8"))
        previous = {c["file"]: c for c in old.get("courses", [])}

    courses = []
    for path in sorted(HERE.glob("*.xrcourse")):
        data = json.loads(path.read_text(encoding="utf-8"))
        outline = (data.get("cfg") or {}).get("outline") or data.get("outline") or {}
        chapters = outline.get("chapters", [])
        prev = previous.get(path.name, {})
        prefix = path.stem.split("-")[0].lower()
        courses.append({
            "id": prev.get("id") or slug(path.stem),
            "file": path.name,
            "title": (outline.get("course") or {}).get("title") or data.get("name") or path.stem,
            "subject": prev.get("subject") or SUBJECTS.get(prefix, {"zh": prefix, "en": prefix.title()}),
            "sections": sum(len(ch.get("sections", [])) for ch in chapters),
            "chapters": len(chapters),
        })
        print(f"{path.name}: {courses[-1]['sections']} sections")

    MANIFEST.write_text(
        json.dumps({
            "version": 1,
            "note": "Built-in sample courses shown in the Projects panel. "
                    "Generated by build_manifest.py — do not hand-edit counts.",
            "courses": courses,
        }, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {MANIFEST.name} — {len(courses)} sample(s)")


if __name__ == "__main__":
    main()
